### ISSUE TITLE
Crashes on MIUI 12

### ISSUE THREAD

**Issue by ghost** [warren-bank/Android-Mock-Location#5]
Hello! I'm having a bit of a specialized problem and I'm hoping you can help. The app keeps crashing every time I click start. I am using a POCO F3 running the unstable weekly builds of the xiaomi.eu ROM for MIUI 12 21.6.16/17. This is the error I am getting:

java.lang.RuntimeException: Unable to start service com.github.warren_bank.mock_location.service.LocationService@d398430 with Intent { act=START cmp=com.github.warren_bank.mock_location/.service.LocationService (has extras) }: java.lang.IllegalArgumentException: powerRequirement is out of range of [1, 3] (too low)
at android.app.ActivityThread.handleServiceArgs(Unknown Source:134)
at android.app.ActivityThread.access$2000(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(Unknown Source:589)
at android.os.Handler.dispatchMessage(Unknown Source:19)
at android.os.Looper.loop(Unknown Source:249)
at android.app.ActivityThread.main(Unknown Source:134)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
Caused by: java.lang.IllegalArgumentException: powerRequirement is out of range of [1, 3] (too low)
at com.android.internal.util.Preconditions.checkArgumentInRange(Unknown Source:61)
at com.android.internal.location.ProviderProperties.<init>(Unknown Source:22)
at android.location.LocationManager.addTestProvider(Unknown Source:33)
at com.github.warren_bank.mock_location.service.looper.MockLocationProvider.<init>(Unknown Source:27)
at com.github.warren_bank.mock_location.service.looper.MockLocationProviderManager.startMockingLocationNetwork(Unknown Source:7)
at com.github.warren_bank.mock_location.service.looper.MockLocationProviderManager.startMockingLocation(Unknown Source:0)
at com.github.warren_bank.mock_location.service.looper.LocationThread.startThread(Unknown Source:2)
at com.github.warren_bank.mock_location.service.looper.LocationThreadManager.start(Unknown Source:38)
at com.github.warren_bank.mock_location.service.LocationService.processIntent(Unknown Source:91)
at com.github.warren_bank.mock_location.service.LocationService.onStart(Unknown Source:0)
at com.github.warren_bank.mock_location.service.LocationService.onStartCommand(Unknown Source:0)
at android.app.ActivityThread.handleServiceArgs(Unknown Source:40)
... 8 more

**Comment by warren-bank** [comment]
Hi. Thanks for the logcat.. that's very helpful.

I'm guessing this crash is related to [issue #4](https://github.com/warren-bank/Android-Mock-Location/issues/4), which was reported yesterday for Android 11 using LineageOS 18.1. Is your ROM based on Android 11, as well?

If so, based on your logcat.. it looks like a very simple fix, which I could try to fix even without having an Android 11 device on-hand. If you'd be willing to test an attempted fix, which wouldn't be ready until later this evening or maybe even tomorrow afternoon.. then I'll look into the issue today.

**Comment by warren-bank** [comment]
[Bam!](https://stackoverflow.com/questions/65065946/changes-in-android-11-no-longer-able-to-provide-mock-location) ..that's exactly [the source](https://github.com/warren-bank/Android-Mock-Location/blob/service/v02.01.07/android-studio-project/Mock-my-GPS/src/main/java/com/github/warren_bank/mock_location/service/looper/MockLocationProvider.java#L31) of the problem

...[here](https://github.com/mcastillof/FakeTraveler/commit/4c05f6fbc971343229f53d1dd32cf3546a584f1e) is FakeTraveler's commit to fix the same problem

**Comment by ghost** [comment]
Thank you very much.

**Comment by warren-bank** [comment]
don't thank me yet :smiley: ...

I just released [v02.01.08](https://github.com/warren-bank/Android-Mock-Location/releases/tag/service%2Fv02.01.08). I'd really appreciate it if you would let me know if this fixes your crash. Thanks!

**Comment by ghost** [comment]
Working like a dream. Finally it is time to walk from one end of the country to the other.
